# This patch is an example of setting arguments for the cAdvisor and prometheus-to-sd
# which cause cAdvisor to collect fewer metrics, and prometheus-to-sd only uploads a few metrics
apiVersion: apps/v1 # for Kubernetes versions before 1.9.0 use apps/v1beta2
kind: DaemonSet
metadata:
  name: cadvisor
spec:
  template:
    spec:
      containers:
      - name: cadvisor
        args:
          - --disable_metrics=percpu,disk,network,tcp,udp # enable only diskIO, cpu, memory
      - name: prometheus-to-sd
        args:
          - --whitelisted-metrics=container_cpu_usage_seconds_total,container_memory_working_set_bytes,container_fs_io_time_seconds_total
